---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1
## @param updateStrategy.type WordPress deployment strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
## e.g:
## updateStrategy:
##  type: RollingUpdate
##  rollingUpdate:
##    maxSurge: 25%
##    maxUnavailable: 25%
##
updateStrategy:
  type: RollingUpdate
## Default Hive image and tag. Please build image locally before applying this.
image:
  name: hive-metastore
  tag: latest
  pullPolicy: IfNotPresent


env:
  HIVE_DB_EXTERNAL: "true"
  HIVE_DB_HOST: "host:port"
  HIVE_DB_NAME: metastore
  HIVE_DB_USER: hive
  HIVE_DB_PASS: hive

## Resource requests and limits: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

service:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90